# Generated by Django 4.1.1 on 2022-10-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='featuredproductcategory',
            options={'verbose_name_plural': 'featured products categories'},
        ),
    ]
