# Generated by Django 4.1.1 on 2022-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cart_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
