# Generated by Django 4.1.1 on 2022-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_personalinfo_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='cart_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='p_id',
            field=models.CharField(max_length=20),
        ),
    ]
