# Generated by Django 4.1.1 on 2022-11-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0006_delete_favorit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=20)),
                ('delivery_person', models.CharField(max_length=100)),
            ],
        ),
    ]
