# Generated by Django 4.1.1 on 2022-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_cart_number_customuser_p_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart_no',
            field=models.CharField(default='', max_length=50, verbose_name='cart number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default='', max_length=50, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p_id',
            field=models.CharField(default='', max_length=50, verbose_name='personal id'),
        ),
    ]
