# Generated by Django 4.1.1 on 2022-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
