# Generated by Django 4.1.1 on 2022-12-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_note',
            field=models.TextField(blank=True),
        ),
    ]
